name: Build and Push
env:
  TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
on:
  push:
    branches: [ restore-patch ]

  release:
    types:
      - edited
      - prereleased
      - released

jobs:

  build:
    name: Build
    if: github.event.action != 'released'
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: build-binaries
      run: |
        git config --global url."https://debianmaster:${TOKEN}@github.com".insteadOf "https://github.com"
        make local
        chmod -R 777 _output

    - uses: docker/build-push-action@v1
      name: publish-cape-velero-upstream-image-branch
      with:
        repository: capesh/cape-velero-upstream
        tag_with_ref: true
        dockerfile: Dockerfile-velero
        username: debianmaster
        add_git_labels: true
        password: ${{secrets.REG_SECRET_DOCKER_HUB}}

    - uses: docker/build-push-action@v1
      name: publish-cape-velero-upstream-image-latest
      with:
        repository: capesh/cape-velero-upstream
        tags: latest
        dockerfile: Dockerfile-velero
        username: debianmaster
        add_git_labels: true
        password: ${{secrets.REG_SECRET_DOCKER_HUB}}

    - name: add plugins
      run: |
        ./hack/cape-custom-scripts.sh
        
    - uses: docker/build-push-action@v1
      name: publish-velero-image
      with:
        repository: capesh/velero
        tag_with_ref: true
        dockerfile: Dockerfile-velero.cape
        username: debianmaster
        password: ${{secrets.REG_SECRET_DOCKER_HUB}}

    - uses: docker/build-push-action@v1
      name: publish-velero-image
      with:
        repository: capesh/velero
        tags: latest,master
        dockerfile: Dockerfile-velero.cape
        username: debianmaster
        password: ${{secrets.REG_SECRET_DOCKER_HUB}}         
